apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: shadgun-com-tls
spec:
  secretName: shadgun-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: shadgun.com
  dnsNames:
    - shadgun.com
    - www.shadgun.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - shadgun.com
          - www.shadgun.com